### ISSUE TITLE
Docs say not to use --offline, but not why

### ISSUE THREAD

**Issue by ringerc** [dgoodwin/tito#141]
The README.md says that --offline is intended to allow use of a local-only git repo without needing to hit a remote server for every action.

However, the asciidoc says:

```
--offline::
do not attempt any remote communication (avoid using
this please)
```

Why? Is this just outdated? Is there something broken that needs fixing?

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/xsuchy/tito/commit/f5f9e22437e48c78429417e834eaa8f33147d107
