### ISSUE TITLE
`tito build` with no args runs but has no effect

### ISSUE THREAD

**Issue by ringerc** [dgoodwin/tito#142]
`tito build` takes `--tgz`, `--rpm` or `--srpm` flags.

If none of these are used, it seems to produce output like:

```
Checking for tag [blah] in git repo [repourl]
Building package [pkgname]
```

but doesn't write anything to the output dir.

I'm using

```
builder = tito.builder.UpstreamBuilder
tagger = tito.tagger.ReleaseTagger
```

in case it matters.

It isn't clear what the intended outcome is. This might deserve an information message for usability.

**Comment by stevekuznetsov** [comment]
This is no longer the case:
```
$ tito build
ERROR: Need an artifact type to build.  Use --rpm, --srpm, or --tgz
```
