### ISSUE TITLE
tito assumes that package sources are in a subdir of the specfile dir

### ISSUE THREAD

**Issue by ringerc** [dgoodwin/tito#145]
Unless I've greatly misunderstood something, it looks like tito assumes that the specfile will be in the root directory of the source tree to prepare and build.

This isn't ideal if you're following an upstream git repo, as it's strongly desirable to contain all the packaging cruft in a subdir like `rpm/` that's simply and easily excluded from dist tarballs, especially when working with UpstreamBuilder.

**Comment by gjanssens** [comment]
I wonder why you closed this issue.
It took me the better part of the morning to figure out one has to cd into the package directory before calling tito build. I still haven't found this explained anywhere in the documentation (unless I missed something). So the (documentation) issue still stands IMO ?

**Comment by ringerc** [comment]
@gjanssens Might be worth opening a new issue (or pull request) with the docs issue and referencing this one.
