### ISSUE TITLE
tito should use git format-patch to produce a patch series

### ISSUE THREAD

**Issue by ringerc** [dgoodwin/tito#147]
It'd be ideal if, when producing packages, tito used `git format-patch` to produce a nicely named and formatted patch series between upstream and the packaged version.

It'd need to insert `Patchn` entries to the spec file to reference them.

The current monolithic patch generation works, but it's very unfriendly toward anybody who needs to unpack the srpm and understand what's going on. It goes against general good packaging practice.

**Comment by ktdreyer** [comment]
I also desire the ability to have individual patches (in the style of `git-format-patch`). This would match much more closely with the way that packages in Fedora and RHEL operate.

**Comment by ringerc** [comment]
Thanks for the comment @xsuchy . I didn't land up using tito for my release and build management as it wasn't a close enough fit and would've required *lots* of changes that might not be useful to others, plus it doesn't use mock, which was a showstopper. So I'm unlikely to tackle implementing patch-series support now.
