### ISSUE TITLE
Is not possible to provide rpmbuild-options when releasing a package

### ISSUE THREAD

**Issue by sergiopena** [dgoodwin/tito#155]
tito build --rpmbuild-options='--nodeps' work flawless but when I try to release a package with this rpmbuild-option the parameter never reaches the builder. 
I've tried with the --arg option, but this provides custom argument to the builder, not to rpmbuild.

**Comment by domcleal** [comment]
#170 should fix this, I just hit the same when trying to --define something from a releaser.
