### ISSUE TITLE
--debug doesn't work

### ISSUE THREAD

**Issue by midnightercz** [dgoodwin/tito#160]
```
tito tag --debug
```

produce nothing new

tests debug flag:

/usr/lib/python2.7/site-packages/tito/common.py in def debug(text, cmd=None)

add
print "DEBUG" in os.environ

run "tito tag --debug" again

Output:
False
..
..

**Comment by stevekuznetsov** [comment]
Today `tito` will use `--debug` to set the `$DEBUG` envar and output as expected:

```python
        self.parser.add_option("--debug", dest="debug", action="store_true",
            help="print debug messages", default=False)
# ...
        if self.options.debug:
            os.environ['DEBUG'] = "true"
```
