### ISSUE TITLE
substitue /rel-eng for /.tito

### ISSUE THREAD

**Issue by xsuchy** [dgoodwin/tito#161]
I find that some projects hesitate to use Tito, because it creates that /rel-eng directory and they take it as unwanted pollution. Yet they are able to accept .tx/, .travis/ etc.

We may get more users if we create /.tito instead of /rel-eng directory.

Opinions? Comments?
I am willing to create backward compatible patch if I get enough +1.

**Comment by jumanjiman** [comment]
:+1:

I like the association with Tito.

I have to point out that .travis.yml and so forth are "extras". One can build project without Travis. Once a project uses Tito, it somewhat forces a workflow. It's a comfortable workflow, but the tie-in is obvious.

**Comment by domcleal** [comment]
:+1:

**Comment by dgoodwin** [comment]
bd (that's a double thumbs up)

**Comment by ktdreyer** [comment]
I always wondered why there was a `rel-eng` directory. I figured it was because tito came from deep inside of Red Hat's rel-eng team?

**Comment by xsuchy** [comment]
@ktdreyer Nope. It was born in Spacewalk git (https://github.com/spacewalkproject/spacewalk) and there have been dozens packages and we kept them in hierarchical and everything release engineer oriented went into /rel-eng/ directory. Even files which were later separated into project which got name Tito. And nobody changed that name, because there was no reason. End of history lesson :)
