### ISSUE TITLE
tito.spec build failure: python_sitelib is undefined on F22+

### ISSUE THREAD

**Issue by domcleal** [dgoodwin/tito#168]
A build of the master branch is failing on Fedora 22 and rawhide, I think because `python_sitelib` in the %files list is undefined.

I'm not sure, but I suspect the `%{!?python2_sitelib: %define python_sitelib` line could be at fault - it's checking for the presence of python**2**_sitelib and then setting python_sitelib, which might be overriding the python_sitelib set inside the python3 conditional above.

https://copr-be.cloud.fedoraproject.org/results/domcleal/tito-nightly/fedora-22-x86_64/tito-0.5.6-1.git.4.4091af9.el6/build.log (http://copr-fe.cloud.fedoraproject.org/coprs/domcleal/tito-nightly/build/87103/)

<pre>
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/usr/share/doc/tito
+ cp -pr README.mkd /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/usr/share/doc/tito
+ cp -pr AUTHORS /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/usr/share/doc/tito
+ cp -pr COPYING /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/usr/share/doc/tito
+ cp -pr doc/builders.mkd /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/usr/share/doc/tito
+ exit 0
RPM build errors:
    Directory not found: /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/tito
    File not found by glob: /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/tito/*
    File not found by glob: /builddir/build/BUILDROOT/tito-0.5.6-1.git.4.4091af9.fc22.x86_64/tito-*.egg-info
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/tito.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 504, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/tito.spec 
LEAVE do --> EXCEPTION RAISED
</pre>

**Comment by stevekuznetsov** [comment]
Closed in #169
