### ISSUE TITLE
[RFE] Provide --quiet switch

### ISSUE THREAD

**Issue by rholy** [dgoodwin/tito#171]
Until #165 is implemented, I'd like to ask you for a `--quiet` command line switch so that my scripts does not print unimportant information, e.g. (in case of `tito build --rpm --builder=mock`):
- `Building package [*]`
- `Creating rpms for * in mock: *`
- `Using srpm: /tmp/tito/*.src.rpm`
- `Initializing mock...`
- `Installing deps in mock...`
- `Building RPMs in mock...`

maybe also (unless the appropriate switches are used explicitly):
- `Wrote: /tmp/tito/*.tar.gz`
- `Wrote: /tmp/tito/*.src.rpm`

Also my tests does not need to print the output of `tito init`.

**Comment by xsuchy** [comment]
It may be worth to switch all those print(s) to log.{info,debug} etc. so users can fine tune the amount of information.

**Comment by jumanjiman** [comment]
> It may be worth to switch all those print(s) to log.{info,debug} etc. so users can fine tune the amount of information.

yes, that would be nice as long as `log` means to print, not syslog.
or else if target is configurable to either tty or syslog.

**Comment by stevekuznetsov** [comment]
This is beginning to be addressed with #264
