### ISSUE TITLE
ReleaseTagger does not work after switch from VersionTagger

### ISSUE THREAD

**Issue by mluscon** [dgoodwin/tito#184]
If I switch my project from VersionTagger to ReleaseTagger and then perform first tag with ReleaseTagger  to e. g. 1.0.0-2, tito does create srpm from upstream sources 1.0.0 and difference patch from 1.0.0-1 to 1.0.0-2, but instead of that produces upstream sources incorrectly marked as version 1.0.0 which actually contains all changes up to 1.0.0-2.

Steps to reproduce:
1. tito tag => my-project-1.0.0-1 built by VersionTagger
2. add some commits
3. exchange VersionTagger to ReleaseTagger and commit tito.props
4. tito tag => my-project-1.0.0-2 built by ReleaseTagger
5. tito build --srpm

**Comment by dgoodwin** [comment]
Hmm, release tagger is for bumping rpm release. It's part of what you want, I think the missing piece is switching your Builder to either UpstreamBuilder or DistributionBuilder, used together this should do what you're looking for.

See man 5 tito.props for info on both those builders and the release tagger. Let me know if that still doesn't work.

**Comment by mluscon** [comment]
Thank you for your help. It seems to be working now with DistributionBuilder.
