### ISSUE TITLE
[rfe] tito tag --specify-version

### ISSUE THREAD

**Issue by FrostyX** [dgoodwin/tito#191]
I am missing something like `--specify-version` for `tito tag` command.

Assume that your project has version `<major.minor.patch>`. When you do `tito tag`, the `patch` number is increased. That's cool, but when you want to increase the `minor` number, you have a problem.

There is simple, but kind of annoying workaround. Opening the spec file in text editor, setting the desired version and then running `tito tag --keep-version`.

I think that something like `tito tag --specify-version <version>` would appreciate many users.

**Comment by domcleal** [comment]
`tito tag --use-version=1.2.3` ?

**Comment by FrostyX** [comment]
Ah, I am sorry. I didn't know about `--use-version`. Can you please note it in manual page?

**Comment by FrostyX** [comment]
Thank you very much for such a quick solution.

**Comment by domcleal** [comment]
No problem!
