### ISSUE TITLE
Add a CoprBuilder

### ISSUE THREAD

**Issue by rholy** [dgoodwin/tito#199]
Since the SRPM upload feature has been added to Copr recently, tito can be [easily](https://github.com/rholy/dnf-stack-ci/blob/5bee4fd78c54178d681540929f89d04a5bc08c2a/dnfstackci.py#L677) integrated with Copr. So it would be nice to ask tito to build a project in Copr.
Here is basically a code which might be modified to be used in `CoprBuilder`: https://github.com/rholy/dnf-stack-ci/blob/5bee4fd78c54178d681540929f89d04a5bc08c2a/dnfstackci.py#L440

**Comment by xsuchy** [comment]
See #198

**Comment by dgoodwin** [comment]
Yeah I like #198, I view pushing to an external build system as a release, and a build as a local only thing. Does that work for everyone?

Being able to upload straight to Copr during release will be great.

**Comment by rholy** [comment]
I am not familiar with `tito release`, let me take a look.

**Comment by rholy** [comment]
So, #198 wouldn't allow me to submit a snapshot (a build from the current HEAD) to Copr, right? It works only with tags, doesn't it?
Would it be possible to support this use case?

**Comment by rholy** [comment]
BTW, using Copr as a builder also e.g. allows one to build RPMs on other architectures than the host's one.

**Comment by dgoodwin** [comment]
tito release --test should build from the current HEAD.

**Comment by rholy** [comment]
Oh, it's not in man pages... Ah, https://github.com/dgoodwin/tito/issues/175...
OK, #198 would be enough for me then, I guess.

**Comment by rholy** [comment]
Heh, it's just few hours old... what a coincidence :D

**Comment by xsuchy** [comment]
BTW you can configure it in config as well. E.g you can put in releaser.conf:
```
[copr-msuchy-test]
releaser = tito.release.CoprReleaser
project_name = copr-dev
builder.test = 1
```
and then `tito release copr-msuchy-test` will create SRPM from latest commit and build it in Copr (see man releasers.conf(5))
