### ISSUE TITLE
Question: Can I use tito to build one rpm from several rams?

### ISSUE THREAD

**Issue by bhtw** [dgoodwin/tito#206]
**Hi** 
We have to start a release/revision control procedure at work and plan to create rpm packages from git repositories that points to all git projects/repositories that belongs to our 1.0 release. We shall then later be able to install that rpm package on remote servers. 

Given we have built an rpm for each repository we want to include in the 1.0 release, is it possible to create one "release_1.0"-rpm file that contains or points to all the wanted rpms?

If tito is not the answer, please point to another tool that might be able to do this if you know of any?

Thanks

**Comment by dgoodwin** [comment]
You could make an empty rpm which has all your other rpms listed as dependencies. Then build and create a yum repository containing all of these, enable the yum repository on end systems, yum install [metadatarpm], which will pull in all the dependencies.

Tito can build the meta-rpm, it can also help publish to a directory and generate the yum metadata for it so it can be used as a yum repository. See "man 5 releasers.conf" and the YumRepoReleaser.
