### ISSUE TITLE
Possible to pass --rpmbuild-options to a releaser?

### ISSUE THREAD

**Issue by jaxxstorm** [dgoodwin/tito#207]
On my test builds, I do this:

```
/usr/bin/tito build --rpmbuild-options="--sign" --rpm --test
```

And it signs the RPM nicely.

I want to do this for a releaser. I tried this:

```
[rsync]
releaser = tito.release.RsyncReleaser
tagger = tito.tagger.VersionTagger
builder = tito.builder.Builder
builder.rpmbuild-options = "--sign"
srpm_disttag = .el6
rsync = host::path
rsync_args = -rlvzpt
filetypes = rpm
```

and a few other things, but got me nowhere. Is this possible?

**Comment by domcleal** [comment]
> builder.rpmbuild-options = "--sign"

This should be `builder.rpmbuild_options` (underscore, not hyphen).

**Comment by jaxxstorm** [comment]
Perfect, thanks!
