### ISSUE TITLE
One step scratch builds with koji?

### ISSUE THREAD

**Issue by jflorian** [dgoodwin/tito#212]
My initial use with tito+koji was to build from SCM and that works well when I want to make a formal release.  For daily development though I don't want clutter git history (or the rpm's changelog) with all my mistakes while I'm crafting up some new feature.  I've since discovered this two step process that works wonderfully:

tito build --test --srpm --dist=.f21
koji build --scratch f21 /tmp/tito/N-V-R.git.?.HASH.f21.src.rpm

Is there a way to do this in a single step?

I'm also curious what determines/sets the value of ? (just prior to HASH) in the 2nd step.  I assume this an ever increasing int to make each successive build newer despite how the HASH might otherwise sort.  If I repeat my two-step process above iteratively with a few "git add ... && git commit --append" ops each time, it doesn't seem that this int increases (and maybe it should/should not).

**Comment by xsuchy** [comment]
from `man releasers.conf`:
       Specify "builder.test = 1" in your releasers.conf target to enable --test builds. (uses the latest git HEAD rather than the latest tagged package) This can be useful for automating the publishing of a nightly build, which you would not want to continually have to tag

It works for all releasers - for `tito.release.KojiReleaser` as well.

The number before HASH is the number of commits since last tag. This way package from next commit has higher NEVR and rpm/dnf treat is as upgrade when you try to install it.
So it does not work very well with --append, where you are changing - instead of adding - last commit.

**Comment by jflorian** [comment]
Oh, once again the subtle distinction of _build_ vs. _release_ in tito has gotten me off on the wrong track at the start.  Since these were development builds that I had no intention of releasing I focused on `tito build` and pretty much ignored `tito release`, especially with TITO(8).  So... a BIG thank you for pointing me in the right direction.

_Please note that I'm running tito-0.6.2-1.fc21_ as I've a mountain to move before I can get off F21 and onto something newer.  _This may bear heavily on the following:_

There's an oddity that I now see which might be a bug.  I have added to my releasers.conf:
```
[test]
builder.test = 1
releaser = tito.release.KojiReleaser
autobuild_tags = f21 f22
```

When I ran `tito release test` I noticed that the two srpms shared the same dist tag:

> Submitting build with: koji build --nowait f21 /tmp/tito/FOO-3.1-1.git.5.2f44541.fc21.src.rpm
> Submitting build with: koji build --nowait f22 /tmp/tito/FOO-3.1-1.git.5.2f44541.fc21.src.rpm

Koji then failed the 2nd build request with 

> GenericError: Build already in progress (task 14541)

This reminded me of issue #159.  So I dropped `f21` from the autobuild_tags and repeated a build test.  Sure enough the srpm still had a dist tag of `.fc21` which reflects my workstation's OS rather than the intended target.  RELEASERS.CONF(5) doesn't mention srpm_disttag being required for the KojiReleaser.  Do I need to split my target into one for each srpm_disttag or is this a genuine bug?

**Comment by jflorian** [comment]
Please disregard my last comment WRT the oddity I saw.  I've since discovered that I merely needed to add something like the following to my tito.props:

```
[f21]
disttag = .fc21

[f22]
disttag = .fc22
```

So I think this ticket can be closed.  Thanks again for the guidance!
