### ISSUE TITLE
tito without "special" tag names

### ISSUE THREAD

**Issue by Ablu** [dgoodwin/tito#222]
Hello,

is it possible to use tito in repositories without forcing the use of "tito tag" on each release?

I basically only want to drop a .spec file into a git repository and have a copr build with webhook which is using the tito build for simply building a new rpm based on a specific branch.

So can i make tito use the tag in "git describe HEAD" somehow?

First I tried without a .tito/packages file. But that always generated non-updateable rpms like `1.git.0.6122afe.fc23`. I digged into the code and figured that the `0` in there is a from a git describe call. But it still always want to build against a specific tag... Can i somehow make it build against the tag in `git describe HEAD`? For me the tag name is 0.16.1. So it does not include the package name (and the tag system cannot be changed). Also I would prefer not to do manual updates to any files when releasing a new version... Is such a use case possible to fulfill with tito?

Regards,
Ablu

**Comment by dgoodwin** [comment]
Not possible today no, you could write a custom builder perhaps though to bypass all expected use of the git tag and do something else. Will be tricky though as the tag is a fairly integral part of the tool and it's definitely always been assumed to be there.

**Comment by xsuchy** [comment]
I thought about it too. When there is no previous tag. There is alway 0. If there is some tag, then the number is "number of commits since last tag". It would be nice to change the semantics to "number of commits since last tag if there is any or number of commits since first commit otherwise". This way packages created by `tito build --test --rpm` on repository without tag will be upgradable.

**Comment by Ablu** [comment]
That would be cool... I am not in a position to force upstream to use a 
special tagging system and even use special tagging commands for 
managing their git repository.

**Comment by xsuchy** [comment]
Should be addressed by https://github.com/dgoodwin/tito/pull/224

**Comment by xsuchy** [comment]
This can be closed as the #224 has been merged.
