### ISSUE TITLE
debug flag should cause run_command to log command, output

### ISSUE THREAD

**Issue by mtinberg** [dgoodwin/tito#253]
I had a problem with tito while debugging a problem with mock that while src/common.py run_command  has the option of logging the command and output if print_on_success is set it only triggers if the subprocess exits non-zero, which mock does not do if /usr/sbin/mock is run instead of /usr/bin/mock, it prints an error and exits 0, which tito does not show even when --debug is set.

If run_command would always print when --debug is set it would make troubleshooting commands that tito uses easier.

**Comment by jmrodri** [comment]
@mtinberg your suggestion is that if '''--debug''' is present, '''run_command'' should print out the following information even if status code was > 0.

```
Command: the command being executed
Status code: the status code returned from above command
Command output: any output from the command
```

I assume having it exit with an error is still acceptable.

**Comment by jmrodri** [comment]
How would this work for you?

```
tito build --test --debug --rpm > o1
```
Basically if --debug is supplied we always print out the Command, Status code, and Command output. If the command succeeds no error. Otherwise, the error is also printed out like it would before.

```
Added lib dir to PYTHONPATH: /home/jesusr/dev/tito/.tito/custom/
---- Builder class is None
Importing tito.builder.Builder
Using builder class: <class 'tito.builder.main.Builder'>
Building in temp dir: /tmp/tito/rpmbuild-titoxo4j_h1g
Getting latest package info from: /home/jesusr/dev/tito/.tito/packages/tito
Command: awk '{ print $1 ; exit }' /home/jesusr/dev/tito/.tito/packages/tito
Status code: 0
Command output: 0.6.9-1

Command: git log --pretty=format:%H --max-count=1 .
Status code: 0
Command output: b04f15a1986acc71a87917a791147d5838e4bdea

tag - tito-0.6.9-1
output - tito-0.6.9-1-3-gb04f15a
Command: git log --pretty=format:%H --max-count=1 .
Status code: 0
Command output: b04f15a1986acc71a87917a791147d5838e4bdea
```
