### ISSUE TITLE
tito tag --use-version option is ignored with ReleaseTagger

### ISSUE THREAD

**Issue by rohanpm** [dgoodwin/tito#274]
The --use-version option to tito tag is ignored if tito.tagger.ReleaseTagger is used.

tito version:

    $ rpm -q tito
    tito-0.6.10-1.el7.noarch

.tito/tito.props:

  [buildconfig]
  builder = tito.builder.Builder
  tagger = tito.tagger.ReleaseTagger
  changelog_do_not_remove_cherrypick = 0
  changelog_format = %s (%ae)

Steps to reproduce:

- Run `tito tag --use-version 1.2.3`, and save changelog

Expected behavior:

tito produces a tag matching <package-name>-1.2.3-<release>, or raises an error telling me it's invalid to use --use-version and ReleaseTagger together.

Actual behavior:

tito behaves the same as if I'd omitted `--use-version` option, and generates a tag by bumping the current Release.

Additional notes:

It works in tito 0.6.9.

**Comment by stevekuznetsov** [comment]
I'll look into this. Thanks for the bug report.

**Comment by stevekuznetsov** [comment]
@rohanpm could you please provide the RPM version of `tito` where this worked in 0.6.9? The change that immediately looks to be the culprit was already in the tree for the 0.6.9 release, so I just want to verify.

**Comment by rohanpm** [comment]
I don't have RPM version - for earlier versions I tested from git tag, installing to virtualenv via "python setup.py install".

At tag tito-0.6.10-1 the problem was reproducible and at tag tito-0.6.9-1 it wasn't.

I thought that commit 6b57b0bcbcbb869 between 0.6.9 and 0.6.10 looked relevant.

**Comment by stevekuznetsov** [comment]
Yeah, a couple things come to mind -- @dgoodwin we should hash out a test matrix for [`VersionTagger._bump_version()`](https://github.com/dgoodwin/tito/blob/master/src/tito/tagger/main.py#L377-L436) -- somewhere along the line the refactor to that method led to this regression but it's hard to reason about as it is factored today.

**Comment by lcarva** [comment]
I'm also seeing this on `tito-0.6.10-1.fc25.noarch`. Downgrading to `tito-0.6.6-1.fc25.noarch` fixes the issue.

**Comment by evgeni** [comment]
Downgrading to `tito-0.6.9-1.fc25.noarch` is enough.

**Comment by evgeni** [comment]
Just run a `git bisect` between 0.6.9 and 0.6.10, it's indeed https://github.com/dgoodwin/tito/commit/6b57b0bcbcbb8695c6bc072b22a0ae59ec0990b3 which breaks this.

**Comment by evgeni** [comment]
The problem with https://github.com/dgoodwin/tito/commit/6b57b0bcbcbb8695c6bc072b22a0ae59ec0990b3 seems to be that it goes on and uses `tito.tagger.main.ReleaseTagger`, not `tito.tagger.main.VersionTagger` (`ReleaseTagger` is what I have in `tito.props`).

The following patch fixes it for me:
```
diff --git a/src/tito/cli.py b/src/tito/cli.py
index 7ec6932..e89de57 100644
--- a/src/tito/cli.py
+++ b/src/tito/cli.py
@@ -653,8 +653,11 @@ def main(self, argv):
             debug("block_tagging defined in tito.props")
             error_out("Tagging has been disabled in this git branch.")
 
-        tagger_class = get_class_by_name(self.config.get(
-            BUILDCONFIG_SECTION, DEFAULT_TAGGER))
+        if self.options.use_version:
+            tagger_class = get_class_by_name("tito.tagger.ForceVersionTagger")
+        else:
+            tagger_class = get_class_by_name(self.config.get(
+                BUILDCONFIG_SECTION, DEFAULT_TAGGER))
         debug("Using tagger class: %s" % tagger_class)
 
         tagger = tagger_class(config=self.config,
```

**Comment by stevekuznetsov** [comment]
Good catch @evgeni. So to reiterate what I commented on the other post -- what would a user expect from a `ReleaseTagger` when they pass `--use-version`? That seems a little nonsensical to me and IMO should be an error.

**Comment by evgeni** [comment]
Well, it might be worth an error. But the behavior until 0.6.10 was exactly that: force the `ForceVersionTagger` if `--use-version` was given. And my patch restores that behavior, but using `VersionTagger`.

The UX problem is, that `VersionTagger` will always create a new version with `release=1`, so it's also not a useful setting for `tito.props` (in my case at least). So till now we would have used `ReleaseTagger` in `tito.props` and rely on the force of the `(Force)VersionTagger` when we pass `--use-version`.

We could introduce `--tagger` (as we have with `tito build --builder`), but that does not really make the UX better, no?

**Comment by stevekuznetsov** [comment]
So in a normal workflow you use the `ReleaseTagger` for incremental updates and then when you are ready to bump a version you `tito tag --use-version`? Incidentally @dgoodwin this was definitely a UX gap for us when we were learning `tito` as well as the tool means you barely ever touch your `.spec` file manually, but the tool seemed to have a gap for anyone that wanted to bump a major version. If we want the `tito tag --use-version` command to fill that gap I understand the argument from @evgeni and agree that it's probably best to force the `VersionTagger`

**Comment by dgoodwin** [comment]
Yeah that was IIRC the intent behind --use-version. It's pretty weird though given how we use taggers, and this bypasses the one you have set. Almost feels like all taggers should have to implement it.

**Comment by stevekuznetsov** [comment]
> Almost feels like all taggers should have to implement it.

What would the `ReleaseTagger` do with it? If I had release 4 would I bump version and also release to 5? If I reset to 1 then it's just  the `VersionTagger` behavior I want.

**Comment by evgeni** [comment]
Yeah, so I want/need either

* version=N, release=R → version=N+1, release=1 (`VersionTagger`)
* version=N, release=R → version=N, release=R+1 (`ReleaseTagger`)

So it would boil down to the fact that I can't choose the tagger on the cli (and the cli offering me `--use-version` and `--use-release` but not all taggers support that).
