### ISSUE TITLE
"release" strategy for Copr

### ISSUE THREAD

**Issue by brianjmurrell** [dgoodwin/tito#281]
I wonder what is a reasonable releaser when building on Copr.  `tito.release.YumRepoReleaser` seems reasonable, but I don't really want to `rsync` my packages anywhere.  They are useful enough right in the Copr project repository without a need to put them anywhere else.

**Comment by dgoodwin** [comment]
Not clear what you mean by being useful right in the Copr project repository? There is a Copr releaser but that would be separate from the Yum releaser. 

The Yum releaser today was meant to pull down a repo and then update and re-push it. I can see a case for generating a releaser that isn't interacting with a remote yum repo, just generating one locally and letting you do whatever you want with it. Maybe LocalYumRepoReleaser or something similar.

**Comment by brianjmurrell** [comment]
> Not clear what you mean by being useful right in the Copr project repository?

I just mean that Copr already creates a working Yum repo for a given project that has Packages in it.  There is no need to push them somewhere else.

> I can see a case for generating a releaser that isn't interacting with a remote yum repo, just generating one locally and letting you do whatever you want with it. Maybe LocalYumRepoReleaser or something similar.

Yes, I think that is what I am probably referring to.

TBH, I'm not sure I quite grasp this process of "release" in the context of tito.  What exactly is it doing?  What is it's purpose?

**Comment by dgoodwin** [comment]
I suspect yum repo releaser is not what you want, there is an explicit Copr releaser, that doesn't involve generating a yum repo which from the sounds of it you don't want at all.

tito releasers are just for publishing the code, we have one for pushing to fedora dist-git, copr, koji, etc. In your case it sounds like Copr releaser is what you want.

**Comment by brianjmurrell** [comment]
So, I have a github "tito repo" in the RPM-per-subdir format with a specfile and tarball in each subdir.  I've created a Copr project to build all of the packages (i.e. in the subdirs) and accordingly created "Package"s in Copr as "tito" sources and for each Package pointed at the github repo and named the subdir.  In Copr I then run **Rebuild** on a Package when I have pushed something new for it to github.

The end goal would be in fact to use Webhooks so that github tells Copr when something new is pushed to the repo and Copr builds it.

I take it that workflow is not quite how the Copr releaser is meant to work is it?

**Comment by dgoodwin** [comment]
Does copr have a pull build mechanism? I wasn't aware.

The tito workflow would be:

- add new tarball to your git repo
- tito tag
- tito release copr to build a srpm and push it to copr

**Comment by brianjmurrell** [comment]
> Does copr have a pull build mechanism? I wasn't aware.

https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks is what I was planning on using.

I suppose using that functionality, I probably don't even want/need to use a tito "releaser" then, yes?

**Comment by xsuchy** [comment]
While you can use webhooks on Pagure and GitHub and it is most comfortable thing, user still may find Copr releaser usefull. Especially if you have project on different system: Gitlab, or its own git repo.

YumRepoReleaser is still useful if you cannot build your package on Copr as there are some legal restrictions. So you can push it to your own repo hosted on your server.

**Comment by brianjmurrell** [comment]
Oh yes.  I was certainly not suggesting that tito's releaser functionality should go away.  I am sure it is useful for lots of use-cases still.

I was just trying to confirm that using Corp/GitHub webhooks as I am, I don't need the releaser functionality, do I?  Is there something it's buying me that I am not seeing?

**Comment by xsuchy** [comment]
This seems to be resolved for some time. You do not need to rsync packages anymore. You can put in releasers.conf
```
[mycopr]
releaser = tito.release.CoprReleaser
project_name = msuchy/myproject
```
and run `tito release mycopr` and it will upload src.rpm directly to Copr.

@dgoodwin you can close this.
