### ISSUE TITLE
tito build --list-tags and --only-tags does not work

### ISSUE THREAD

**Issue by xsuchy** [dgoodwin/tito#29]
$ rpm -q tito
tito-0.4.2-1.git.7.2b17927.fc16.noarch

[msuchy@dri/~/rhn/spacewalk.pub/backend{master}]$ tito build --list-tags
Checking for tag [spacewalk-backend-1.6.58-1] in git repo [ssh://msuchy@git.fedorahosted.org/git/spacewalk.git/]
Building package [spacewalk-backend-1.6.58-1]
[msuchy@dri/~/rhn/spacewalk.pub/backend{master}]$ tito build --only-tags=dist-5E-sw-1.6-candidate
Usage: tito build [options]

tito: error: no such option: --only-tags

Additionally --only-tags is present in man page, but not in --help output.

**Comment by TomasTomecek** [comment]
3 years later, `--only-tags` is still in manpage.
