### ISSUE TITLE
Why there wasn't a release for 10 months?

### ISSUE THREAD

**Issue by TomasTomecek** [dgoodwin/tito#308]
I would love to use the feature contributed by @vrutkovs where I can specify the tag format. Unfortunately I can't, since there wasn't a release for such a long time. Please, make one, give us a Christmas present.

**Comment by dgoodwin** [comment]
https://copr.fedorainfracloud.org/coprs/dgoodwin/tito/

https://bodhi.fedoraproject.org/users/dgoodwin

**Comment by TomasTomecek** [comment]
Thank you, that was quick!
