### ISSUE TITLE
build without quiet tries to run cp with a glob, with no plan to expand the glob

### ISSUE THREAD

**Issue by aecolley** [dgoodwin/tito#316]
Since tito-0.6.11-1.el7.centos.noarch appeared on CentOS 7, "tito build" runs have been failing. A stacktrace is below. The problem is that `_build_in_mock` calls either `run_command_print` or `run_command` depending on the `quiet` flag, but those functions treat their arguments differently.

`run_command` feeds the command to a shell (`commands.getstatusoutput`), which expands glob patterns. However, `run_command_print` merely splits the command on whitespace and feeds it to `subprocess.Popen` with the implied `shell=False` default parameter; therefore there is no shell which might expand the glob.

Proposed fix: change `run_command_print` to use `shell=True` instead of `shlex.split`.

```
Command output: ["cp: cannot stat '/tmp/tmp.EqTGC8kPk3/rpmdump/rpmbuild-murgatroydazCRcx/mockoutput/*.rpm': No such file or directory"]

Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 378, in main
    return builder.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 156, in run
    self.rpm()
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 1139, in rpm
    self._build_in_mock()
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 1166, in _build_in_mock
    (mock_output_dir, self.rpmbuild_basedir))
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 468, in run_command_print
    raise RunCommandException(command, status, "\n".join(output))
tito.exception.RunCommandException: Error running command: cp -v /tmp/tmp.EqTGC8kPk3/rpmdump/rpmbuild-murgatroydazCRcx/mockoutput/*.rpm /tmp/tmp.EqTGC8kPk3/rpmdump
```

**Comment by aecolley** [comment]
Caused by #316

**Comment by mtinberg** [comment]
I haven't had the time to research back and repro the problem I was having but this seems exactly like what I guessed was happening.  Either approach would likely fix the problem, consistently using a subshell which can expand globs, or avoid relying on shell globbing and external commands for operations which can be done in python directly.

**Comment by ernestask** [comment]
#318 was merged, this seems to work now.
