### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ernestask** [dgoodwin/tito#347]
As had been done in https://github.com/dgoodwin/tito/issues/308, I’m asking for a new release, since it’s been almost two years and the code accumulated fixes for important issues (https://github.com/dgoodwin/tito/issues/316).

On a related note, should there be an organization with more than one person governing the development? While the software is still useful, it would be a shame to let everything wither and die.

**Comment by FrostyX** [comment]
@dgoodwin, we have discussed this with @xsuchy this week. If you want, I can do (this) release.

**Comment by dgoodwin** [comment]
This would be great, thank you @FrostyX, do I need to do anything to enable permissions or can you do this just by virtue of being a Fedora packager.

I've tried in the past to find additional maintainers in the company but have struggled to get anything to stick. I am unfortunately away from tito and not even using it for my work for several years now. :(

**Comment by FrostyX** [comment]
> do I need to do anything to enable permissions or can you do this just by virtue of being a Fedora packager.

I seem to have permissions for this git repo, so that should be fine. AFAIK you need to add me only here -  https://src.fedoraproject.org/rpms/tito . Please go to the "Settings" and then "Users & Groups"

**Comment by dgoodwin** [comment]
What is your Fedora username @FrostyX

**Comment by FrostyX** [comment]
> What is your Fedora username @FrostyX

frostyx :smile:

**Comment by dgoodwin** [comment]
now an admin, thx!

**Comment by FrostyX** [comment]
I've created PR#348 to fix the spec file for EPEL8. Do you want to merge anything else before doing the release? I've tried

    python3 ./runtests.py
    hacking/runtests.sh

and got no error. I will do some manual testing tomorrow and tag the packages. They build successfully in Copr - https://copr.fedorainfracloud.org/coprs/frostyx/tito/build/1121708/ (that's the one with patched spec).

**Comment by dgoodwin** [comment]
Nothing on my end, sounds great, thank you.

**Comment by FrostyX** [comment]
New version `tito-0.6.12` was released and is now in stable Fedora repos.
Release notes: https://github.com/dgoodwin/tito/releases/tag/tito-0.6.12-1

I am closing the issue.
