### ISSUE TITLE
Release tarball not uploaded: 0.6.12

### ISSUE THREAD

**Issue by glensc** [dgoodwin/tito#357]
_After https://github.com/dgoodwin/tito/issues/355 announcement I was puzzled, what is Tito, so as first action I started to package it for [PLD Linux](https://www.pld-linux.org/) and I have noticed the fedora .spec refers to tarball that is not uploaded_

The tarball specified in Fedora .spec is missing from release page:

```
[~/fc/tito(ERR) (master)] ➔ grep Source *.spec
Source0: https://github.com/dgoodwin/tito/archive/tito-%{version}.tar.gz
```

- https://src.fedoraproject.org/rpms/tito/blob/7e361d2f44e73e110d90f582335eebf26e5566fa/f/tito.spec#_26

so this left me question: Does the project need prepared tarball and upload, or can just use GitHub automatically generated git snapshot, i.e:

- https://github.com/dgoodwin/tito/archive/tito-0.6.12-1.tar.gz

**Comment by FrostyX** [comment]
Hello @glensc,
In master we already have 

    # Sources can be obtained by
    # git clone https://github.com/dgoodwin/tito.git
    # cd tito
    # tito build --tgz
    Source0: %{name}-%{version}.tar.gz

I am going to tag 0.6.13 very soon, so we will have it released.

**Comment by glensc** [comment]
@FrostyX, will you upload the `.tar.gz` to release then? so the rpm package can be made **without** Tito (bootstrap build).

PS, Initial PLD Linux package I've created:
- https://github.com/pld-linux/tito

**Comment by FrostyX** [comment]
I guess this is the same thing that @praiskup was also asking for?

**Comment by FrostyX** [comment]
In my opinion, we should create a releaser for that. Then I would change the workflow and start uploading packages. What do you think?

**Comment by glensc** [comment]
Downstream distro packagers expect upstream to provide tarball of their software. 

If the package can be produced from git export that GitHub provides for each git tag, the manual tarball upload is not necessary.

**Comment by praiskup** [comment]
> the manual tarball upload is not necessary

Are you 100% sure that the snapshot tarball will be the byte-by-byte the same after 3 years,
15, 50 years?

**Comment by praiskup** [comment]
Of course I didn't read the whole story here before;  it is project decision
whether they rely on GitHub snapshots.

First, tito does some manual tweaks in released tarball, and anyways, for
pedantic people - tito should allow people to upload the real released tarball
that will stay consistent forever (even if git, tar, or compression changed, or
if GitHub disappeared).

**Comment by FrostyX** [comment]
@glensc, so I checked how other projects managed by tito do it (e.g. [mock]()) and they upload the tarball, so I am going to do that also. I've already uploaded the 0.6.12. Please see
https://github.com/dgoodwin/tito/releases/tag/tito-0.6.12-1

**Comment by FrostyX** [comment]
AFAIK we don't have any tito releaser for that yet, so I am going to file an RFE and hopefully, we can automatize that step in the future.

**Comment by FrostyX** [comment]
I have created a document describing how to properly release the tito package, so nobody will have an excuse to forget on uploading the tarball. Please see PR#361.

I think we can close this issue now?

**Comment by praiskup** [comment]
See #322
